# This file was generated by GoReleaser. DO NOT EDIT.
class Nextver < Formula
  desc "Automatic semver versioning"
  homepage "https://github.com/craftypath/nextver/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/craftypath/nextver/releases/download/v0.2.0/nextver_0.2.0_darwin_amd64.tar.gz"
    sha256 "09a93f1fe280c263adbfcaee71f66c9d33b05230bc6415b9d0f376107a0b91b4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/craftypath/nextver/releases/download/v0.2.0/nextver_0.2.0_linux_amd64.tar.gz"
      sha256 "289f0b7471af3d722e50f4bf2c081af746d5cf2c20bd3b8cf9cb61aa6e981e26"
    end
  end

  def install
    bin.install "nextver"
  end

  test do
    system "#{bin}/nextver --version"
  end
end
