# This file was generated by GoReleaser. DO NOT EDIT.
class Nextver < Formula
  desc "Automatic semver versioning"
  homepage "https://github.com/craftypath/nextver/"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/craftypath/nextver/releases/download/v0.3.0/nextver_0.3.0_darwin_amd64.tar.gz"
    sha256 "f70e1b8dc218654cf9d7cee4e2be7c82e8499847cdd464f2c1f915b6f18eec36"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/craftypath/nextver/releases/download/v0.3.0/nextver_0.3.0_linux_amd64.tar.gz"
      sha256 "e6c33109b98f9f02939ccf42f87226a95829ff117bc3b69df1e1e65afd3aaa2e"
    end
  end

  def install
    bin.install "nextver"
  end

  test do
    system "#{bin}/nextver --version"
  end
end
